import type { AdminRole } from "@/domain/enums";

/** Permission catalog for Hubsom Admin RBAC. */
export const PERMISSIONS = [
  "dashboard:view",
  "users:view",
  "users:manage",
  "sellers:view",
  "sellers:manage",
  "sellers:verify",
  "drivers:view",
  "drivers:manage",
  "drivers:verify",
  "documents:review",
  "payments:view",
  "payments:manage",
  "payouts:view",
  "payouts:manage",
  "orders:view",
  "orders:manage",
  "deliveries:view",
  "deliveries:manage",
  "map:view",
  "streams:view",
  "streams:manage",
  "auctions:view",
  "auctions:manage",
  "products:view",
  "products:manage",
  "categories:manage",
  "moderation:view",
  "moderation:manage",
  "reviews:manage",
  "support:view",
  "support:manage",
  "promotions:manage",
  "notifications:send",
  "analytics:view",
  "fraud:view",
  "fraud:manage",
  "security:view",
  "security:manage",
  "settings:view",
  "settings:manage",
  "audit:view",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL = [...PERMISSIONS];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  super_admin: ALL,
  finance_admin: [
    "dashboard:view",
    "payments:view",
    "payments:manage",
    "payouts:view",
    "payouts:manage",
    "orders:view",
    "analytics:view",
    "settings:view",
    "audit:view",
  ],
  support_admin: [
    "dashboard:view",
    "users:view",
    "users:manage",
    "sellers:view",
    "drivers:view",
    "orders:view",
    "orders:manage",
    "deliveries:view",
    "support:view",
    "support:manage",
    "reviews:manage",
  ],
  moderation_admin: [
    "dashboard:view",
    "users:view",
    "users:manage",
    "sellers:view",
    "sellers:manage",
    "products:view",
    "products:manage",
    "streams:view",
    "streams:manage",
    "auctions:view",
    "moderation:view",
    "moderation:manage",
    "reviews:manage",
    "fraud:view",
    "fraud:manage",
  ],
  operations_admin: [
    "dashboard:view",
    "sellers:view",
    "sellers:verify",
    "drivers:view",
    "drivers:manage",
    "drivers:verify",
    "documents:review",
    "orders:view",
    "orders:manage",
    "deliveries:view",
    "deliveries:manage",
    "map:view",
    "streams:view",
    "streams:manage",
    "auctions:view",
    "auctions:manage",
    "products:view",
    "categories:manage",
    "promotions:manage",
    "notifications:send",
    "analytics:view",
    "settings:view",
  ],
};

export function roleHasPermission(role: AdminRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export const ROLE_LABELS: Record<AdminRole, string> = {
  super_admin: "Super Admin",
  finance_admin: "Finance Admin",
  support_admin: "Support Admin",
  moderation_admin: "Moderation Admin",
  operations_admin: "Operations Admin",
};
